#### FOR TESTING PURPOSES ONLY ####
### Please use the security_orig.yaml before going in production ###
## This file is responsible for a deactivated authentication process ##
# Endpoints are not secured! #

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AuthUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            security: false

        api:
            pattern:   ^/api
            security: false

#### FOR TESTING PURPOSES ONLY ####
### Please use the security_orig.yaml before going in production ###
## This file is responsible for a deactivated authentication process ##
# Endpoints are not secured! #