version: "3"
services:
    nginx:
        build:
            context: ./build/nginx
            dockerfile: Dockerfile
        volumes:
            - /home/fsn/nutzerdatenbank-backend:/var/www/project/:cached
        ports:
            - 8082:80
        networks:
            - symfony_app
            - db_network
    
    fpm:
        build:
            context: ./build/php-fpm
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=mysql://root:opwer384@mysql/nutzerdatenbank
        volumes:
            - /home/fsn/nutzerdatenbank-backend:/var/www/project/:cached
        networks:
            - symfony_app
            - db_network

networks:
  traefik_net:
    external: true
  db_network:
    external: true
  symfony_app:
    external: true