name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Nginx Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-nginx:latest docker/build/nginx
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-nginx:latest

      - name: Build and Push PHP-FPM Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-php-fpm:latest docker/build/php-fpm
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-php-fpm:latest
